num = int(input("Enter a decimal number: "))
bin=lambda x : format(x,'b')
print("Equivalent binary number is",bin(num))
oct=lambda x : format(x,'o')
print("Equivalent octal number is",oct(num))
hex=lambda x : format(x,'x')
print("Equivalent hexadecimal number is",hex(num))